#debug: true
#定义应用访问端口以及应用根路径
server:
  port: 9003
  context-path: /

#定义应用名称
spring: 
  application:
    name: eureka9003

eureka:
  instance:
    hostname: eureka9003
    port: 9003
    appname: eureka9003
  client:
    register-with-eureka: false #表示是否将自己注册在EurekaServer上
    fetch-registry: true  #表示是否从EurekaServer获取注册信息
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
       defaultZone: http://eureka9001:9001/eureka,http://eureka9002:9002/eureka

  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000

