spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
         server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
server:
  port: 8016
logging:
  level:
    root: info
    org.springframework: info