#debug: false
spring:
  application:
#提供eurekaserver的名称
    name: cloud-platform-producer
server:
  port: 8002
  servlet:
    ####context-path: /
    context-path: /producercontext
eureka:
  instance:
#提供别的服务调用的名称
    appname: cloud-platform-producer
  client:
    serviceUrl:
      defaultZone: http://eureka9001:9001/eureka/,http://eureka9002:9002/eureka/,http://eureka9003:9003/eureka/
jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: this is a key
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592