server:
  port: 8050
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  ##开启从注册中心动态创建路由功能，利用微服务服务名行进路由
      routes:
      - id: route-consunmer      ####路由ID，没有固定规则，但要唯一
        ###uri: lb://fsh-house   ####匹配后提供服务的路由地址
        ##uri: http://localhost:8001   ####匹配后提供服务的路由地址----静态路由：写固定地址
        uri:  lb://cloud-platform-consumer   ####匹配后提供服务的路由地址--------动态路由：用服务名弄
        predicates:
        - Path=/consunmer/**      ################断言,路径匹配的进行路由

      - id: route-producer        ####路由ID，没有固定规则，但要唯一
        ##uri: http://localhost:8002   ####匹配后提供服务的路由地址----静态路由：写固定地址
        uri: lb://cloud-platform-producer    ####匹配后提供服务的路由地址----动态路由：用服务名弄
        predicates:
        - Path=/**      ################断言,路径匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway
    prefer-ip-address: true
    ####服务提供者provider注册进eureka列表内
  client:
    service-url:
      defaultZone: http://eureka9001:9001/eureka/,http://eureka9002:9002/eureka/,http://eureka9003:9003/eureka/
###########开启actuator管理api，后面关闭
management:
  endpoints:
    web:
      exposure:
        include: '*'
        #############后面关闭
  security:
    enabled: false